controller_list:
  - name: fake_talos_arm_controller
    joints:
      - body_to_shoulder
      - shoulder_to_upper_arm
      - upper_arm_to_elbow_bracket
      - elbow_bracket_to_elbow_block
      - elbow_block_to_lower_arm